spring:
  application:
    name: LibraryManagementSystem

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library_management_system
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
